export interface ColorTypes {
  background: string;
  containerBackground: string;
  titleGreen: string;
  titleDefault: string;
  signInUpButton: string;
  signInUpButtonTextColor: string;
  placeholder: string;
  warning: string;
  profileBackground: string;
  profilePanel: string;
  profileButton: string;
  profileTitle: string;
  profileContainer: string;
  profileIcon: string;
  budgetTitle: string;
  tabBar: string;
  iconContainer: string;
  onBoardingBackground: string;
  onBoardingContainer: string;
  onBoardingTextContainer: string;
  onBoardingText: string;
  onBoardingSkip: string;
  missionCenterBackground: string;
  missionCenterTitle: string;
  gray: string;
  activeBackgroundColor: string;
  inActiveBackgroundColor: string;
  borderActiveColor: string;
  borderInActiveColor: string;
  wishlistBackground: string;
  wishlistTitle: string;
  wishlistProgressBar: string;
  wishlistUnfilledProgress: string;
  wishlistSubcontent: string;
  roundButtonContainer: string;
  roundButton: string;
  roundButtonSave: string;
  roundButtonApprove: string;
  topBoardItems: string;
  misssionContentText: string;
  categoryText: string;
  badgeCollectionBackground: string;
  infoCard: string;
  contentCard: string;
  quizCard: string;
  currencyEuro: string;
  currenyDolar: string;
  currencyTitle: string;
}

export const LightTheme: ColorTypes = {
  background: '#EFEFEF',
  containerBackground: '#FFFFFF',
  titleGreen: '#89E3B5',
  titleDefault: 'black',
  signInUpButton: 'black',
  signInUpButtonTextColor: 'white',
  placeholder: 'gray',
  warning: 'orange',
  profileBackground: '#EFEFEF',
  profilePanel: '#62E4C6',
  profileButton: 'white',
  profileTitle: 'white',
  profileContainer: 'white',
  profileIcon: 'black',
  budgetTitle: '#3CD598',
  tabBar: '#FFFFFF',
  iconContainer: '#CEF4E5',
  onBoardingBackground: '#FFBD12',
  onBoardingContainer: '#FFFFFF',
  onBoardingTextContainer: '#00C6AE',
  onBoardingText: 'black',
  onBoardingSkip: '#474A57',
  missionCenterBackground: '#FFBD12',
  missionCenterTitle: 'black',
  gray: 'gray',
  activeBackgroundColor: '#9ee3fb',
  inActiveBackgroundColor: '#3c4145',
  borderActiveColor: '#86c3d7',
  borderInActiveColor: '#1c1c1c',
  wishlistBackground: '#D6FCF7',
  wishlistTitle: 'black',
  wishlistProgressBar: '#32FC65',
  wishlistUnfilledProgress: '#A5FCCB',
  wishlistSubcontent: 'black',
  roundButtonContainer: 'white',
  roundButton: '#FFD956',
  roundButtonSave: '#18191F',
  roundButtonApprove: '#FFD956',
  topBoardItems: '#61E4C5',
  misssionContentText: 'black',
  categoryText: '#333',
  badgeCollectionBackground: '#299657',
  infoCard: '#B0E3CF',
  contentCard: '#90BEFF',
  quizCard: '#FCB351',
  currencyEuro: '#FFBD12',
  currenyDolar: '#F95A2B',
  currencyTitle: 'white',
};

export const DarkTheme: ColorTypes = {
  background: '#27282E',
  containerBackground: '#404040',
  titleGreen: '#89E3B5',
  titleDefault: 'white',
  signInUpButton: 'white',
  signInUpButtonTextColor: 'black',
  placeholder: 'white',
  warning: 'orange',
  profileBackground: '#27282E',
  profilePanel: '#3A8A77',
  profileButton: '#404040',
  profileTitle: 'white',
  profileContainer: '#404040',
  profileIcon: 'white',
  budgetTitle: '#3CD598',
  tabBar: '#18191F',
  iconContainer: '#1E3732',
  onBoardingBackground: '#27282E',
  onBoardingContainer: '#404040',
  onBoardingTextContainer: '#638074',
  onBoardingText: '#292929',
  onBoardingSkip: '#ACACAC',
  missionCenterBackground: '#27282E',
  missionCenterTitle: '#FFBD12',
  gray: 'gray',
  activeBackgroundColor: '#9ee3fb',
  inActiveBackgroundColor: '#3c4145',
  borderActiveColor: '#86c3d7',
  borderInActiveColor: '#1c1c1c',
  wishlistBackground: '#18191F',
  wishlistTitle: '#A9A9A9',
  wishlistProgressBar: '#4E4F53',
  wishlistUnfilledProgress: '#333439',
  wishlistSubcontent: '#D2D2D2',
  roundButtonContainer: '#A9A9A9',
  roundButton: '#A9A9A9',
  roundButtonSave: '#D2D2D2',
  roundButtonApprove: '#A9A9A9',
  topBoardItems: '#FFBD12',
  misssionContentText: '#DADADA',
  categoryText: 'white',
  badgeCollectionBackground: '#18191F',
  infoCard: '#617D72',
  contentCard: '#5C7AA3',
  quizCard: '#AC7B37',
  currencyEuro: '#18191F',
  currenyDolar: '#18191F',
  currencyTitle: '#A9A9A9',
};

const themes = {
  light: {...LightTheme},
  dark: {...DarkTheme},
};

export const getThemeColor = (theme: 'light' | 'dark' = 'light') => {
  const themeMode = themes[theme];
  return themeMode;
};
