//Sign Up Action Types
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
//Sign In Action Types
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const UPDATEBUDGETSUCCESS = 'UPDATEBUDGETSUCCESS';
export const UPDATEBUDGETFAILURE = 'UPDATEBUDGETFAILURE';

export const ADDEXPENSESSUCCESS = 'ADDEXPENSESFAILURE';
export const ADDEXPENSESFAILURE = 'ADDEXPENSESFAILURE';
