//Sign Up Action Types
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
//Sign In Action Types
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
//Logout Action Types
export const LOGOUT = 'LOGOUT';
//On Boarding Seen Action Types
export const SETONBOARDINGSEEN = 'SETONBOARDINGSEEN';
//Budget Action Types
export const UPDATEBUDGETSUCCESS = 'UPDATEBUDGETSUCCESS';
export const UPDATEBUDGETFAILURE = 'UPDATEBUDGETFAILURE';
//Expense Action Types
export const ADDEXPENSESSUCCESS = 'ADDEXPENSESFAILURE';
export const ADDEXPENSESFAILURE = 'ADDEXPENSESFAILURE';
//Wishlist Action Types
export const ADDWISHLISTSUCCESS = 'ADDWISHLISTSUCCESS';
export const ADDWISHLISTFAILURE = 'ADDWISHLISTFAILURE';
export const DELETEWISHLISTSUCCESS = 'DELETEWISHLISTSUCCESS';
export const DELETEWISHLISTFAILURE = 'DELETEWISHLISTFAILURE';
export const UPDATEWISHLISTSUCCESS = 'UPDATEWISHLISTSUCCESS';
export const UPDATEWISHLISTFAILURE = 'UPDATEWISHLISTFAILURE';
//Mission Action Types
export const UPDATESCORE = 'UPDATESCORE';
export const SETEXPENSEADDED = 'SETEXPENSEADDED';
export const SETDAILYLOGIN = 'SETDAILYLOGIN';
export const SETMONEYBOXSUCCESS = 'SETMONEYBOXSUCCESS';
export const SETCURRENCYADDED = 'SETCURRENCYADDED';
export const RESETSTORE = 'RESETSTORE';
export const UPDATEEXPENSEADDED = 'UPDATEEXPENSEADDED';
export const WISHLISTCOMPLETED = 'WISHLISTCOMPLETED';
