import {StyleSheet} from 'react-native';
import {scale, verticalScale, moderateScale} from 'react-native-size-matters';

export const styles = StyleSheet.create({
  containerHorizontal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: verticalScale(20),
    width: scale(50),
  },
  buttonContainerHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: 'white',
    borderRadius: 25,
    maxWidth: scale(110),
    borderWidth: 2,
    alignSelf: 'flex-end',
  },
  roundButton: {
    width: scale(33),
    height: scale(33),
    borderRadius: 25,
    backgroundColor: '#FFD956',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'black',
    borderWidth: 2,
    borderBottomWidth: 4,
    zIndex: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 24,
  },
  insideContainerHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 20,
    width: scale(33),
    height: scale(33),
    marginLeft: scale(4),
    zIndex: 1,
  },
  inputHorizontal: {
    height: verticalScale(30),
    marginLeft: scale(-25),
    borderWidth: 1,
    borderRadius: 55,
    width: scale(58),
    borderBlockColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    backgroundColor: 'white',
    paddingHorizontal: scale(8),
    fontWeight: '900',
    alignItems: 'center',
    alignContent: 'center',
    fontSize: 15,
    zIndex: 1,
    textAlign: 'right',
  },
  saveButtonHorizontal: {
    backgroundColor: '#18191F',
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(4),
    marginLeft: scale(-15),
    zIndex: 0,
  },
  saveButtonText: {
    color: '#fff',
  },
  icon: {
    width: '70%',
    height: '70%',
  },
  containerVertical: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: scale(50),
  },
  insideContainerVertical: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 20,
    width: scale(30),
    height: verticalScale(100),
    zIndex: 1,
    marginTop: verticalScale(-5),
  },
  changeButton: {
    backgroundColor: '#18191F',
    width: scale(25),
    paddingVertical: verticalScale(-20),
    borderRadius: 10,
    marginTop: verticalScale(8),
    height: verticalScale(22),
    zIndex: 0,
    alignItems: 'center',
  },
  changeButtonText: {
    color: '#FFD956',
    fontSize: 20,
  },
  buttonContainerVertical: {
    flexDirection: 'column',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: 'white',
    borderRadius: 25,
    maxHeight: verticalScale(95),
    borderWidth: 2,
    alignSelf: 'center',
    marginTop: verticalScale(-25),
  },
  moneySaveIcon: {
    width: scale(17),
    height: verticalScale(30),
  },
});
