import {StyleSheet} from 'react-native';
import {scale, verticalScale, moderateScale} from 'react-native-size-matters';

export const styles = StyleSheet.create({
  containerHorizontal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: verticalScale(20),
    width: 50,
  },
  buttonContainerHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: 'white',
    borderRadius: 25,
    padding: 0,
    maxWidth: 125,
    borderWidth: 2,
    alignSelf: 'flex-end',
  },
  roundButton: {
    width: 40,
    height: 40,
    borderRadius: 25,
    backgroundColor: '#FFD956',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'black',
    borderWidth: 2,
    borderBottomWidth: 4,
    zIndex: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 24,
  },
  insideContainerHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 20,
    width: 40,
    height: 40,
    marginLeft: 5,
    zIndex: 1,
  },
  inputHorizontal: {
    height: 40,
    marginLeft: -30,
    borderWidth: 1,
    borderRadius: 55,
    width: 70,
    borderBlockColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    backgroundColor: 'white',
    paddingHorizontal: 12,
    fontWeight: '900',
    alignItems: 'center',
    alignContent: 'center',
    fontSize: 15,
    zIndex: 1,
    textAlign: 'right',
  },
  saveButtonHorizontal: {
    backgroundColor: '#18191F',
    paddingHorizontal: 26,
    paddingVertical: 5,
    borderRadius: 0,
    marginLeft: -20,
    zIndex: 0,
  },
  saveButtonText: {
    color: '#fff',
  },
  icon: {
    width: '70%',
    height: '70%',
  },
  containerVertical: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 50,
  },
  insideContainerVertical: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 20,
    width: 30,
    height: 100,
    zIndex: 1,
    marginTop: -5,
  },
  changeButton: {
    backgroundColor: '#18191F',
    width: 30,
    paddingVertical: -20,
    borderRadius: 10,
    marginTop: 10,
    height: 30,
    zIndex: 0,
    alignItems: 'center',
  },
  changeButtonText: {
    color: '#FFD956',
    marginTop: 0,
    fontSize: 20,
  },
  buttonContainerVertical: {
    flexDirection: 'column',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: '#FFD956',
    borderRadius: 25,
    padding: 0,
    maxHeight: 125,
    borderWidth: 2,
    alignSelf: 'center',
    marginTop: -30,
  },
  moneySaveIcon: {
    width: 20,
    height: 30,
  },
});
